[workspace]
members = [
    "ownership",
    "traits",
    "errorhandling",
    "iterators",
    "cargotest",
    "cargotestlib",
    "asref",
    "multithreading",
    "tokio-echo",
    "chat-axum",
]
